name: SciProProject
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - absl-py=2.3.1
  - astunparse=1.6.3
  - backports.zstd=1.2.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2025.11.12
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2025.11.12
  - charset-normalizer=3.4.4
  - contourpy=1.3.3
  - cycler=0.12.1
  - flatbuffers=24.12.23
  - fonttools=4.61.1
  - freetype=2.14.1
  - gast=0.7.0
  - giflib=5.2.2
  - google-pasta=0.2.0
  - grpcio=1.67.1
  - h2=4.3.0
  - h5py=3.15.1
  - hdf5=1.14.6
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - joblib=1.5.3
  - keras=3.12.0
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.4
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcurl=8.17.0
  - libcxx=21.1.8
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgrpc=1.67.1
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libml_dtypes-headers=0.5.4
  - libnghttp2=1.67.0
  - libopenblas=0.3.30
  - libpng=1.6.53
  - libprotobuf=5.28.3
  - libre2-11=2024.07.02
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libtensorflow_cc=2.18.0
  - libtensorflow_framework=2.18.0
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - markdown=3.10
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - mdurl=0.1.2
  - ml_dtypes=0.4.0
  - munkres=1.1.4
  - namex=0.1.0
  - ncurses=6.5
  - numpy=2.4.0
  - openjpeg=2.5.4
  - openssl=3.6.0
  - opt_einsum=3.4.0
  - optree=0.18.0
  - packaging=25.0
  - pandas=2.3.3
  - pillow=12.0.0
  - pip=25.3
  - protobuf=5.28.3
  - pthread-stubs=0.4
  - pygments=2.19.2
  - pyparsing=3.3.1
  - pysocks=1.7.1
  - python=3.12.12
  - python-dateutil=2.9.0.post0
  - python-flatbuffers=25.9.23
  - python-tzdata=2025.3
  - python_abi=3.12
  - pytz=2025.2
  - qhull=2020.2
  - re2=2024.07.02
  - readline=8.3
  - requests=2.32.5
  - rich=14.2.0
  - scikit-learn=1.8.0
  - scipy=1.16.3
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.2
  - tensorboard=2.18.0
  - tensorboard-data-server=0.7.0
  - tensorflow=2.18.0
  - tensorflow-base=2.18.0
  - tensorflow-estimator=2.18.0
  - termcolor=3.2.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tornado=6.5.4
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025c
  - unicodedata2=17.0.0
  - urllib3=2.6.2
  - werkzeug=3.1.4
  - wheel=0.45.1
  - wrapt=2.0.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zipp=3.23.0
  - zlib-ng=2.3.2
  - zstd=1.5.7

prefix: "/Users/vali/miniforge3/envs/SciProProject"
